const mlbTeams = [
  { 
    teamAbv: "ARI",
    teamID: 109,
    displayName: "Arizona Diamondbacks",
    primary: '#A71930',
    secondary: '#E3D4AD',
  },
  {
    teamAbv: "ATL",
    teamID: 144,
    displayName: "Atlanta Braves",
    primary: '#CE1141',
    secondary: '#13274F',
  },
  { 
    teamAbv: "BAL",
    teamID: 110,
    displayName: "Baltimore Orioles",
    primary: '#DF4601',
    secondary: '#000000',
  },
  { 
    teamAbv: "BOS",
    teamID: 111,
    displayName: "Boston Red Sox",
    primary: '#BD3039',
    secondary: '#0C2340',
  },
  { 
    teamAbv: "CHC",
    teamID: 112,
    displayName: "Chicago Cubs",
    primary: '#0E3386',
    secondary: '#CC3433',
  },
  { 
    teamAbv: "CWS",
    teamID: 145,
    displayName: "Chicago White Sox",
    primary: '#27251F',
    secondary: '#C4CED4',
  },
  { 
    teamAbv: "CIN",
    teamID: 113,
    displayName: "Cincinnati Reds",
    primary: '#C6011F',
    secondary: '#000000',
  },
  { 
    teamAbv: "CLE",
    teamID: 114,
    displayName: "Cleveland Guardians",
    primary: '#0C2340',
    secondary: '#E31937',
  },
  { 
    teamAbv: "COL",
    teamID: 115,
    displayName: "Colorado Rockies",
    primary: '#33006F',
    secondary: '#C4CED4',
  },
  { 
    teamAbv: "DET",
    teamID: 116,
    displayName: "Detroit Tigers",
    primary: '#0C2340',
    secondary: '#FA4616',
  },
  { 
    teamAbv: "HOU",
    teamID: 117,
    displayName: "Houston Astros",
    primary: '#002D62',
    secondary: '#EB6E1F',
  },
  { 
    teamAbv: "KC",
    teamID: 118,
    displayName: "Kansas City Royals",
    primary: '#004687',
    secondary: '#BD9B60',
  },
  { 
    teamAbv: "LAA",
    teamID: 108,
    displayName: "Los Angeles Angels",
    primary: '#003263',
    secondary: '#BA0021',
  },
  { 
    teamAbv: "LAD",
    teamID: 119,
    displayName: "Los Angeles Dodgers",
    primary: '#005A9C',
    secondary: '#A5ACAF',
  },
  { 
    teamAbv: "MIA",
    teamID: 146,
    displayName: "Miami Marlins",
    primary: '#00A3E0',
    secondary: '#000000',
  },
  { 
    teamAbv: "MIL",
    teamID: 158,
    displayName: "Milwaukee Brewers",
    primary: '#FFC52F',
    secondary: '#12284B',
  },
  { 
    teamAbv: "MIN",
    teamID: 142,
    displayName: "Minnesota Twins",
    primary: '#002B5C',
    secondary: '#D31145',
  },
  { 
    teamAbv: "NYM",
    teamID: 121,
    displayName: "New York Mets",
    primary: '#002D72',
    secondary: '#FF5910',
  },
  { 
    teamAbv: "NYY",
    teamID: 147,
    displayName: "New York Yankees",
    primary: '#0C2340',
    secondary: '#C4CED3',
  },
  { 
    teamAbv: "OAK",
    teamID: 133,
    displayName: "Oakland Athletics",
    primary: '#003831',
    secondary: '#EFB21E',
  },
  { 
    teamAbv: "PHI",
    teamID: 143,
    displayName: "Philadelphia Phillies",
    primary: '#E81828',
    secondary: '#002D72',
  },
  { 
    teamAbv: "PIT",
    teamID: 134,
    displayName: "Pittsburgh Pirates",
    primary: '#27251F',
    secondary: '#FDB827',
  },
  { 
    teamAbv: "STL",
    teamID: 138,
    displayName: "St. Louis Cardinals",
    primary: '#C41E3A',
    secondary: '#0C2340',
  },
  { 
    teamAbv: "SD",
    teamID: 135,
    displayName: "San Diego Padres",
    primary: '#2F241D',
    secondary: '#FFC425',
  },
  { 
    teamAbv: "SF",
    teamID: 137,
    displayName: "San Francisco Giants",
    primary: '#FD5A1E',
    secondary: '#27251F',
  },
  { 
    teamAbv: "SEA",
    teamID: 136,
    displayName: "Seattle Mariners",
    primary: '#0C2C56',
    secondary: '#005C5C',
  },
  { 
    teamAbv: "TB",
    teamID: 139,
    displayName: "Tampa Bay Rays",
    primary: '#092C5C',
    secondary: '#8FBCE6',
  },
  { 
    teamAbv: "TX",
    teamID: 140,
    displayName: "Texas Rangers",
    primary: '#003278',
    secondary: '#C0111F',
  },
  { 
    teamAbv: "TOR",
    teamID: 141,
    displayName: "Toronto Blue Jays",
    primary: '#134A8E',
    secondary: '#1D2D5C',
  },
  { 
    teamAbv: "WAS",
    teamID: 120,
    displayName: "Washington Nationals",
    primary: '#AB0003',
    secondary: '#14225A',
  }
]

export default mlbTeams
